name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm test:unit

      - name: Run lint
        run: pnpm lint

      - name: Run format check
        run: pnpm format:check

      - name: Build
        run: pnpm build
        continue-on-error: true  # Known issue with miniprogram-automator types

      - name: Type check
        run: pnpm typecheck
        continue-on-error: true  # Known issue with miniprogram-automator types

      - name: Verify tool count
        run: |
          OUTPUT=$(pnpm update-readme 2>&1)
          TOOL_COUNT=$(echo "$OUTPUT" | grep "📊 Total:" | sed 's/.*Total: \([0-9]*\) tools.*/\1/')
          if [ "$TOOL_COUNT" != "65" ]; then
            echo "❌ Tool count mismatch: expected 65, got $TOOL_COUNT"
            exit 1
          fi
          echo "✅ Tool count verified: 65 tools"

  smoke-test:
    name: Smoke Test
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run smoke test
        run: bash scripts/smoke-test.sh
